#!/bin/bash
# Verify that traces generated by step 04 reach the TempoStack.
#
# Strategy: query the Jaeger v3 API on tempo-smoke-query-frontend for our
# service ("mcoa-traces-smoke"), retrying for up to ~3 minutes to ride out
# ingester flush latency.

set -euo pipefail

NAMESPACE="${NAMESPACE:-chainsaw-mcoa-traces-smoke}"
SERVICE="mcoa-traces-smoke"
HOST="tempo-smoke-query-frontend.${NAMESPACE}.svc.cluster.local:16686"

# Spawn a sidecar pod with curl + jq to query the in-cluster service.
oc -n "${NAMESPACE}" run check-traces \
  --image=registry.access.redhat.com/ubi9/ubi-minimal:latest \
  --restart=Never --rm -i --quiet -- \
  sh -c "microdnf install -y jq curl >/dev/null 2>&1 || true
        for i in \$(seq 1 36); do
          body=\$(curl -fsS \"http://${HOST}/api/services\" 2>/dev/null || echo '{}')
          if echo \"\$body\" | jq -e '.data[]? | select(. == \"${SERVICE}\")' >/dev/null 2>&1; then
            echo \"FOUND service ${SERVICE} after \$((i*5))s\"
            curl -fsS \"http://${HOST}/api/traces?service=${SERVICE}&limit=5\" | jq '.data | length'
            exit 0
          fi
          echo \"attempt \$i: service ${SERVICE} not yet visible\"
          sleep 5
        done
        echo \"TIMEOUT: service ${SERVICE} never appeared in Tempo\"
        exit 1"
