#!/bin/bash
# Verify that traces generated by step 04 reach the TempoStack.
#
# Strategy: run a Job that queries the Jaeger v3 API on the in-cluster
# tempo-smoke-query-frontend service for our service ("mcoa-traces-smoke"),
# retrying for up to ~3 minutes to ride out ingester flush latency.
#
# Uses curlimages/curl (curl baked in) so the pod doesn't need to install
# packages at runtime. Uses a plain grep instead of jq to avoid a second
# dependency.

set -euo pipefail

NAMESPACE="${NAMESPACE:-chainsaw-mcoa-traces-smoke}"
SERVICE="mcoa-traces-smoke"
HOST="tempo-smoke-query-frontend.${NAMESPACE}.svc.cluster.local:16686"

oc -n "${NAMESPACE}" delete job check-traces --ignore-not-found --wait=true >/dev/null 2>&1 || true

cat <<EOF | oc -n "${NAMESPACE}" apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: check-traces
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check-traces
          image: curlimages/curl:8.10.1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          command:
            - sh
            - -c
            - |
              for i in \$(seq 1 36); do
                body=\$(curl -fsS "http://${HOST}/api/services" 2>/dev/null || echo '')
                if printf '%s' "\$body" | grep -q '"${SERVICE}"'; then
                  echo "FOUND service ${SERVICE} after \$((i*5))s"
                  echo "--- traces ---"
                  curl -fsS "http://${HOST}/api/traces?service=${SERVICE}&limit=5" \\
                    | head -c 200
                  echo
                  exit 0
                fi
                echo "attempt \$i: service ${SERVICE} not yet visible (body=\${body:0:120})"
                sleep 5
              done
              echo "TIMEOUT"
              exit 1
EOF

# Wait for either success or failure (whichever lands first).
oc -n "${NAMESPACE}" wait --for=condition=complete --timeout=4m job/check-traces &
WAIT_OK=$!
oc -n "${NAMESPACE}" wait --for=condition=failed   --timeout=4m job/check-traces &
WAIT_FAIL=$!
wait -n "$WAIT_OK" "$WAIT_FAIL" || true

oc -n "${NAMESPACE}" logs -l job-name=check-traces --tail=-1 || true
oc -n "${NAMESPACE}" get job check-traces -o jsonpath='{.status.succeeded}' | grep -q 1
